export { default as ArrowLeft } from './ArrowLeft'
export { default as Burger } from './Burger'
export { default as Cross } from './Cross'
export { default as Monkey } from './Monkey'
export { default as Heart } from './Heart'
export { default as Mind } from './Mind'
export { default as Dislike } from './Dislike'
